spring:
  datasource:
    username: client_agency
    password: client_agency
    url: jdbc:mysql://localhost:3306/client_agency

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never  
